apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-serviceaccount
  namespace: api
  labels:
    app.kubernetes.io/part-of: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-role
  namespace: api
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-rolebinding
  namespace: api
subjects:
  - kind: ServiceAccount
    name: api-serviceaccount
    namespace: api
roleRef:
  kind: Role
  name: api-role
  apiGroup: rbac.authorization.k8s.io