apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.fullname }}-headless"
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.fullname }}
  ports:
    - name: api
      port: 9000
      targetPort: 9000
