apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.fullname }}-service"
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "{{ .Values.fullname }}-tcp-api"
      port: {{ .Values.service.ports.api }}
      targetPort: {{ .Values.service.ports.api }}
  selector:
    app: {{ .Values.fullname }}
