{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Values.fullname }}-servicemonitor"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: minio
spec:
  endpoints:
    - port: tcp-api
      path: /minio/v2/metrics/cluster
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/component: minio
      app.kubernetes.io/part-of: minio
{{- end }}