apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: storage
spec:
  clusterIP: None # this is what makes it headless
  selector:
    app: minio
  ports:
  - name: minio-api
    port: 9000
    targetPort: 9000
    protocol: TCP